[package]
name = "simple-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std = "1.1"
cw2 = "0.10"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1 