name: Build CosmWasm Contracts for Juno

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'cosmos-contracts/**'
      - '.github/workflows/optimize-wasm.yml'

jobs:
  build-juno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install cargo-wasm
        run: cargo install cargo-wasm --locked

      - name: Build CosmWasm Contracts
        working-directory: ./cosmos-contracts
        run: |
          for pkg in escrow resolver simple-test; do
            echo "Building $pkg..."
            (cd $pkg && cargo wasm)
          done

      - name: Collect wasm artifacts
        working-directory: ./cosmos-contracts
        run: |
          mkdir -p artifacts
          find . -name "*.wasm" -exec cp {} artifacts/ \;
          echo "Available artifacts:"
          ls -la artifacts/

      - name: Upload wasm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: juno-wasm-artifacts
          path: cosmos-contracts/artifacts/*.wasm 